site_name: KOBPIU
theme:
  name: material
markdown_extensions:
  - attr_list
nav:
    - Public Identity Utility: index.md
    - Usecase:
        - Public Identity Utility: usecase.md
        - Business Usecase: business.md
    - License: license.md









